package com.capstoneprojectg8.schoolscheduleapp.utils

import android.content.Context
import android.content.res.Configuration
import com.capstoneprojectg8.schoolscheduleapp.R
import kotlin.random.Random

object ThemeHelper {
    fun isDarkModeEnabled(context: Context): Boolean {
        val mode = context.resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK
        return mode == Configuration.UI_MODE_NIGHT_YES
    }

    fun getRandomColor(): Int {
        val colorNames = arrayListOf(
            R.color.purple_200,
            R.color.purple_500,
            R.color.teal_200,
            R.color.teal_700,
            R.color.aqua,
            R.color.Aquamarine,
            R.color.Blue,
            R.color.BlueViolet,
            R.color.Brown,
            R.color.BurlyWood,
            R.color.CadetBlue,
            R.color.Chartreuse,
            R.color.Chocolate,
            R.color.Coral,
            R.color.CornflowerBlue,
            R.color.Crimson,
            R.color.Cyan,
            R.color.DarkCyan,
            R.color.DarkGoldenrod,
            R.color.DarkGreen,
            R.color.DarkKhaki,
            R.color.DarkMagenta,
            R.color.DarkOliveGreen,
            R.color.DarkOrange,
            R.color.DarkOrchid,
            R.color.DarkRed,
            R.color.DarkSalmon,
            R.color.DarkSeaGreen,
            R.color.DarkSlateBlue,
            R.color.DarkSlateGray,
            R.color.DarkTurquoise,
            R.color.DarkViolet,
            R.color.DeepPink,
            R.color.DeepSkyBlue,
            R.color.DimGray,
            R.color.DodgerBlue,
            R.color.FireBrick,
            R.color.ForestGreen,
            R.color.Fuchsia,
            R.color.gray,
            R.color.Green,
            R.color.GreenYellow,
            R.color.HotPink,
            R.color.IndianRed,
            R.color.LawnGreen,
            R.color.LightCoral,
            R.color.LightGoldenrodYellow,
            R.color.LightGreen,
            R.color.LightPink,
            R.color.LightSalmon,
            R.color.LightSeaGreen,
            R.color.LightSkyBlue,
            R.color.LightSlateGray,
            R.color.LightSteelBlue,
            R.color.lime,
            R.color.LimeGreen,
            R.color.Magenta,
            R.color.MediumAquamarine,
            R.color.MediumOrchid,
            R.color.MediumPurple,
            R.color.MediumSeaGreen,
            R.color.MediumSlateBlue,
            R.color.MediumSpringGreen,
            R.color.MediumTurquoise,
            R.color.MediumVioletRed,
            R.color.olive,
            R.color.Olive,
            R.color.OliveDrab,
            R.color.Orange,
            R.color.OrangeRed,
            R.color.Orchid,
            R.color.PaleGoldenrod,
            R.color.PaleGreen,
            R.color.PaleVioletRed,
            R.color.Peru,
            R.color.Pink,
            R.color.Plum,
            R.color.purple,
            R.color.red,
            R.color.RosyBrown,
            R.color.RoyalBlue,
            R.color.SaddleBrown,
            R.color.Salmon,
            R.color.SandyBrown,
            R.color.SeaGreen,
            R.color.Sienna,
            R.color.SlateBlue,
            R.color.SpringGreen,
            R.color.SteelBlue,
            R.color.Tan,
            R.color.teal,
            R.color.Teal,
            R.color.Tomato,
            R.color.Violet,
            R.color.YellowGreen,
            R.color.orange,
            R.color.green,
            R.color.blue,
        )


        val randomArrayIndex = Random.nextInt(colorNames.size)
        return colorNames[randomArrayIndex]
    }
}